// Copyright(c) 2026 The Rainway AI Gateway (壬远AI网关) Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

package iintent_config

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/rainway-ai-gateway/ai-gateway-api/lib/xerror"
)

// Defaults and bounds applied by the control plane. They mirror the
// intent_config table column defaults (see db_ddl.sql) and are kept
// deliberately stricter than the BFE protocol limits (255): relaxing a bound
// only needs a control-plane constant change, never a BFE change.
const (
	// DefaultMinConfidence is applied when the optional global gate is omitted.
	DefaultMinConfidence = 0.6

	// maxIntentQuestions is the control-plane cap of the questions array; an
	// empty array is the documented soft switch that disables intent
	// classification (all intent conditions never match, traffic falls back
	// to the default route).
	maxIntentQuestions = 10

	// minQuestionOptions/maxQuestionOptions bound the criteria/levels count
	// of a single question.
	minQuestionOptions = 1
	maxQuestionOptions = 10
)

// Question types (same vocabulary as BFE mod_ai_intent).
const (
	QuestionTypeChoice = "choice"
	QuestionTypeScore  = "score"
)

// IntentConfigFixedID is the fixed primary key of the singleton row
// (single-row overwrite storage).
const IntentConfigFixedID = int64(1)

// intentConfigVersionLayout is the version timestamp layout (yyyyMMddHHmmss).
const intentConfigVersionLayout = "20060102150405"

// IntentConfig is the storage-level AI intent configuration: a global
// singleton persisted as a single overwritten row (fixed id, no history
// versions, no enabled column).
type IntentConfig struct {
	Id            int64
	Version       string
	MinConfidence float64
	Questions     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// IntentConfigParam is the Open API representation of the singleton (lowercase
// vocabulary). Questions keeps the JSON passthrough contract: the control
// plane validates the whole document but stores/returns the raw JSON text so
// the BFE-side file structure stays the single frozen source of truth.
// Version is an internal field of the distribution pipeline and is never
// exposed through the Open API.
type IntentConfigParam struct {
	MinConfidence *float64        `json:"min_confidence"`
	Questions     json.RawMessage `json:"questions"`
	CreatedAt     *time.Time      `json:"created_at"`
	UpdatedAt     *time.Time      `json:"updated_at"`
}

// IntentConfigStorager defines storage operations for the intent config
// singleton. Upsert is executed inside a transaction provided by
// itxn.TxnStorager.
type IntentConfigStorager interface {
	// Upsert overwrites the singleton row (insert when absent, overwrite
	// when present; fixed id=1). The version is generated by the manager
	// and written along with the row.
	Upsert(ctx context.Context, config *IntentConfig) error
	// Fetch reads the singleton row; returns nil, nil when no config has
	// ever been published (the unpublished state is not an error).
	Fetch(ctx context.Context) (*IntentConfig, error)
}

// intentQuestion is the temporary validation structure used to validate the
// questions JSON document (see design-docs/sys-design/details/意图配置与导出.md
// section 4.3; same criteria as BFE mod_ai_intent questions_conf.go, with the
// control-plane caps above).
type intentQuestion struct {
	Name          string            `json:"name"`
	Type          string            `json:"type"`
	Instructions  string            `json:"instructions"`
	Criteria      map[string]string `json:"criteria"`
	Levels        []*intentLevel    `json:"levels"`
	MinConfidence *float64          `json:"min_confidence"`
}

type intentLevel struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

// ValidateIntentConfig validates the singleton document as a whole: questions
// must be a JSON array of 0-10 questions (empty array = soft switch to
// disable intent classification); every question must satisfy the shared
// criteria (unique non-empty name, type choice|score, non-empty instructions,
// criteria/levels mutually exclusive and required by type with 1-10 entries,
// option names free of '|', min_confidence within [0,1] both globally and
// per question). Any failure rejects the whole PUT.
func ValidateIntentConfig(param *IntentConfigParam) error {
	if param == nil {
		return xerror.WrapParamErrorWithMsg("intent config is required")
	}

	questions, err := parseIntentQuestions(param.Questions)
	if err != nil {
		return err
	}

	nameSet := map[string]struct{}{}
	for i, question := range questions {
		if question == nil {
			return xerror.WrapParamErrorWithMsg("intent question #%d is null", i)
		}

		if question.Name == "" {
			return xerror.WrapParamErrorWithMsg("intent question #%d name is required", i)
		}
		if _, ok := nameSet[question.Name]; ok {
			return xerror.WrapParamErrorWithMsg("duplicate intent question name: %s", question.Name)
		}
		nameSet[question.Name] = struct{}{}

		if question.Type != QuestionTypeChoice && question.Type != QuestionTypeScore {
			return xerror.WrapParamErrorWithMsg("intent question %s type must be %s or %s, got %s",
				question.Name, QuestionTypeChoice, QuestionTypeScore, question.Type)
		}
		if question.Instructions == "" {
			return xerror.WrapParamErrorWithMsg("intent question %s instructions is required", question.Name)
		}
		if err := validateConfidence(question.MinConfidence,
			fmt.Sprintf("intent question %s min_confidence", question.Name)); err != nil {
			return err
		}

		switch question.Type {
		case QuestionTypeChoice:
			if len(question.Levels) != 0 {
				return xerror.WrapParamErrorWithMsg("intent question %s levels not allowed for choice", question.Name)
			}
			if len(question.Criteria) < minQuestionOptions || len(question.Criteria) > maxQuestionOptions {
				return xerror.WrapParamErrorWithMsg("intent question %s criteria count must be within [%d,%d], got %d",
					question.Name, minQuestionOptions, maxQuestionOptions, len(question.Criteria))
			}
			for option := range question.Criteria {
				if option == "" {
					return xerror.WrapParamErrorWithMsg("intent question %s contains empty option name", question.Name)
				}
				if strings.Contains(option, "|") {
					return xerror.WrapParamErrorWithMsg("intent question %s option name %s contains '|'",
						question.Name, option)
				}
			}
		case QuestionTypeScore:
			if len(question.Criteria) != 0 {
				return xerror.WrapParamErrorWithMsg("intent question %s criteria not allowed for score", question.Name)
			}
			if len(question.Levels) < minQuestionOptions || len(question.Levels) > maxQuestionOptions {
				return xerror.WrapParamErrorWithMsg("intent question %s levels count must be within [%d,%d], got %d",
					question.Name, minQuestionOptions, maxQuestionOptions, len(question.Levels))
			}
			seen := map[string]struct{}{}
			for j, level := range question.Levels {
				if level == nil {
					return xerror.WrapParamErrorWithMsg("intent question %s level #%d is null", question.Name, j)
				}
				if level.Name == "" {
					return xerror.WrapParamErrorWithMsg("intent question %s level #%d name is required", question.Name, j)
				}
				if _, ok := seen[level.Name]; ok {
					return xerror.WrapParamErrorWithMsg("intent question %s duplicate level name: %s",
						question.Name, level.Name)
				}
				seen[level.Name] = struct{}{}
			}
		}
	}

	return validateConfidence(param.MinConfidence, "min_confidence")
}

// parseIntentQuestions parses and bounds the questions JSON document. The
// empty array is the documented soft switch and stays valid.
func parseIntentQuestions(raw json.RawMessage) ([]*intentQuestion, error) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 || bytes.Equal(trimmed, []byte("null")) {
		return nil, xerror.WrapParamErrorWithMsg("intent config questions is required")
	}

	var questions []*intentQuestion
	if err := json.Unmarshal(trimmed, &questions); err != nil {
		return nil, xerror.WrapParamErrorWithMsg("intent config questions must be a JSON array: %s", err.Error())
	}
	if len(questions) > maxIntentQuestions {
		return nil, xerror.WrapParamErrorWithMsg("intent config questions count must be <= %d, got %d",
			maxIntentQuestions, len(questions))
	}

	return questions, nil
}

func validateConfidence(confidence *float64, topic string) error {
	if confidence == nil {
		return nil
	}
	if *confidence < 0 || *confidence > 1 {
		return xerror.WrapParamErrorWithMsg("%s %f out of range [0,1]", topic, *confidence)
	}
	return nil
}

// newConfigVersion generates the version timestamp for a PUT (yyyyMMddHHmmss,
// bumped +1s past the stored version when both fall in the same second, so
// every PUT strictly increases the version).
func newConfigVersion(current *IntentConfig) string {
	version := time.Now().Format(intentConfigVersionLayout)
	if current == nil {
		return version
	}

	stored, err := time.ParseInLocation(intentConfigVersionLayout, current.Version, time.Local)
	if err != nil {
		return version
	}

	next := stored.Add(time.Second).Format(intentConfigVersionLayout)
	if version < next {
		return next
	}
	return version
}

// intentConfigToParam converts the storage-level singleton into the Open API
// representation (version/id stay internal and are not exposed).
func intentConfigToParam(config *IntentConfig) *IntentConfigParam {
	if config == nil {
		return nil
	}

	return &IntentConfigParam{
		MinConfidence: &config.MinConfidence,
		Questions:     json.RawMessage(config.Questions),
		CreatedAt:     &config.CreatedAt,
		UpdatedAt:     &config.UpdatedAt,
	}
}

// intentConfigParamToStorage converts the Open API document into the
// storage-level row. The global min_confidence defaults to
// DefaultMinConfidence when omitted; questions keep their raw JSON text.
func intentConfigParamToStorage(param *IntentConfigParam, version string) *IntentConfig {
	minConfidence := DefaultMinConfidence
	if param.MinConfidence != nil {
		minConfidence = *param.MinConfidence
	}

	return &IntentConfig{
		Id:            IntentConfigFixedID,
		Version:       version,
		MinConfidence: minConfidence,
		Questions:     string(param.Questions),
	}
}
